---
driver:
  name: vagrant
  cache_directory: false

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: fort-pinecone
    data_bags_path: test/integration/default/data_bags
    run_list:
      - recipe[acme_server]
      - recipe[install-fake-root-certificate]
      - recipe[fort-pinecone::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      acme:
        dir: https://127.0.0.1:14000/dir
        contact:
          - mailto:admin@example.com