source 'https://supermarket.chef.io'
metadata

cookbook 'user'
cookbook 'sudo'

cookbook 'fail2ban'

cookbook 'poise-service'

# Http
cookbook 'acme', github: 'schubergphilis/chef-acme', ref: '2871ed6'
cookbook 'nginx'

# Gitlab
cookbook 'omnibus-gitlab'

# RocketChat
cookbook 'sc-mongodb'
cookbook 'nodejs'

group :integration do
  cookbook 'install-fake-root-certificate',
    path: 'test/fixtures/cookbooks/install-fake-root-certificate'

  cookbook 'acme_server',
    github: 'schubergphilis/chef-acme',
    rel:    'test/fixtures/cookbooks/acme_server',
    ref:    '2871ed6'
end