#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'fort-pinecone', path: '.'

cookbook 'user'
cookbook 'sudo'

cookbook 'fail2ban'

cookbook 'poise-service'

# Http
cookbook 'acme', github: 'schubergphilis/chef-acme', ref: '2871ed6'
cookbook 'nginx'

# Gitlab
cookbook 'omnibus-gitlab'

# RocketChat
cookbook 'sc-mongodb'
cookbook 'nodejs'

# Test cookbooks
cookbook 'install-fake-root-certificate',
  path: 'test/fixtures/cookbooks/install-fake-root-certificate'

cookbook 'acme_server',
  github: 'schubergphilis/chef-acme',
  path: 'test/fixtures/cookbooks/acme_server'
