#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'fort-pinecone', path: '.'

cookbook 'user'
cookbook 'sudo'
cookbook 'acme', github: 'schubergphilis/chef-acme'
cookbook 'nginx'

# Test cookbooks
cookbook 'install-fake-root-certificate',
  path: 'test/fixtures/cookbooks/install-fake-root-certificate'

cookbook 'acme_server',
  github: 'schubergphilis/chef-acme',
  path: 'test/fixtures/cookbooks/acme_server'
